### ISSUE TITLE
make rinstaller failing

### ISSUE THREAD

**Issue by aadler** [r-windows/r-installer#10] opened 2019-12-19 04:03 UTC
Hi, Jeroen.

Using the older version of miktex, **not** updating, and installing some packages, and setting install-on-the fly seems to have worked. I'm not closing Issue https://github.com/r-windows/r-testing/issues/7 yet because I want to test a fresh build instead of `make manuals` on an existing.

That being said, invoking `make rinstaller` on the version which completed the manuals errors out as per the log below. Any thoughts?

Thank you!

```
$ make rinstaller
make[1]: Entering directory '/c/rtools40/R-devel/src/gnuwin32/installer'
rm -f -R R-devel
mkdir R-devel
cp -pR ../../../bin ../../../modules R-devel
mkdir -p R-devel/library
cp -pR  ../../../library/base  ../../../library/tools  ../../../library/utils  ..../../library/grDevices  ../../../library/graphics  ../../../library/stats  ../..../library/datasets  ../../../library/methods  ../../../library/grid  ../../../lirary/splines  ../../../library/stats4  ../../../library/tcltk  ../../../library/cmpiler  ../../../library/parallel  ../../../library/MASS  ../../../library/lattic  ../../../library/Matrix  ../../../library/nlme  ../../../library/survival  .././../library/boot  ../../../library/cluster  ../../../library/codetools  ../../../ibrary/foreign  ../../../library/KernSmooth  ../../../library/rpart  ../../../libary/class  ../../../library/nnet  ../../../library/spatial  ../../../library/mgcv ../../../library/translations R-devel/library
rm -f R-devel/library/*/MD5
rm -f R-devel/*/Makefile.in
mkdir -p R-devel/etc/x64
cp -p ../../../etc/Rprofile.site ../../../etc/Rconsole ../../../etc/Rdevga ../.././etc/rgb.txt ../../../etc/repositories ../../../etc/Rcmd_environ R-devel/etc
if test -f "../../../etc/curl-ca-bundle.crt"; then \
  cp -p "../../../etc/curl-ca-bundle.crt" R-devel/etc; \
fi
cp -p ../../../etc/x64/Makeconf R-devel/etc/x64
mkdir -p R-devel/doc
cp -p ../../../doc/CRAN_mirrors.csv R-devel/doc
cp -p ../../../doc/BioC_mirrors.csv R-devel/doc
mkdir -p R-devel/doc/manual/images
cp -pR ../../../doc/html R-devel/doc
cp -p ../../../doc/manual/*.html ../../../doc/manual/*.pdf \
  R-devel/doc/manual
cp -p ../../../doc/manual/images/*.png R-devel/doc/manual/images
rm -f R-devel/doc/manual/R-FAQ.pdf
rm -f R-devel/doc/html/R-admin.html
rm -f R-devel/doc/html/index-default.html
cp -p ../../../COPYING ../../../README R-devel
cp -p ../../../doc/AUTHORS ../../../doc/COPYING ../../../doc/FAQ ../../../doc/RESURCES ../../../doc/THANKS ../../../doc/CHANGES ../../../doc/NEWS ../../../doc/NEW.0 ../../../doc/NEWS.1 ../../../doc/NEWS.2 R-devel/doc
cp -p ../COPYRIGHTS ../README.Rterm ../../../doc/manual/rw-FAQ R-devel/doc
cp -p R-devel/doc/CHANGES R-devel
sed -e s/@RWVER@/R-devel/g \
  -e s/@RVER@//g \
  -e "s/@FULLVERSION@/`cat ../../../VERSION`/g" ../README > R-devel/README.R-deve
sed -e 3,5d ../README.packages > R-devel/doc/README.packages
zip -q dosfiles.zip R-devel/* R-devel/doc/*
unzip -qao dosfiles.zip
rm -f dosfiles.zip
cp -p ../../../doc/NEWS.pdf R-devel/doc
cp -p ../../../doc/NEWS.rds ../../../doc/CHANGES.rds R-devel/doc
mkdir -p R-devel/share \
  R-devel/src/library R-devel/src/gnuwin32
cp ../../../doc/html/logo.jpg ../../../doc/html/Rlogo.svg R-devel/doc/html
cp ../../../doc/KEYWORDS* R-devel/doc
cp -pR ../../../include R-devel
cp -pR ../../../share/R ../../../share/dictionaries ../../../share/encodings .././../share/licenses ../../../share/make ../../../share/Rd ../../../share/texmf .././../share/zoneinfo R-devel/share
(cd ..; make --no-print-directory PKGDIR=. pkgclean-windlgs)
cp -pR ../windlgs R-devel/src/library
sed -e 's!^BINPREF [?]= .*!BINPREF ?= /mingw64/bin/!' \
  ../../../etc/x64/Makeconf > R-devel/etc/x64/Makeconf
mkdir R-devel/tests
make --no-print-directory -C ../../../tests -f Makefile.win \
  INST_TO=../src/gnuwin32/installer/R-devel/tests install-tests
find R-devel -name .svn -prune -exec rm -Rf \{\} \;
find R-devel -name \*~ -delete
echo "make.packages.html(.Library,temp=FALSE,verbose=FALSE)" | R-devel/bin/x64/Rterm.exe --vanilla --no-echo LC_COLLATE=C
cp -pRf ../../../Tcl R-devel
rm -f R-devel/Tcl*/lib/*.lib
------------ not including 32-bit files
for f in ; do \
  cp "$f" R-devel/bin/i386; \
done
for f in ; do \
  cp "$f" R-devel/bin/x64; \
done
adding MD5 checksums
../../../bin/x64/Rscript JRins.R \
  R-devel R-devel 0 \
  1 R-core "C:/R/Inno"
"C:/R/Inno/iscc" R.iss > R-devel.log 2>&1
make[1]: *** [Makefile:175: R-devel-win.exe] Error 2
make[1]: Leaving directory '/c/rtools40/R-devel/src/gnuwin32/installer'
make: *** [Makefile:388: rinstaller] Error 2
```

**Comment by jeroen** [comment] 2020-01-30 21:27
Can you test if this issue still exists if you follow instructions from the readme?

**Comment by jeroen** [comment] 2020-02-11 22:23
I think the problem is fixed. I tried with the latest `basic-miktex-2.9.7342-x64.exe` and afterward update all latex packages via the admin panel. And then I was able to build R.

**Comment by jeroen** [comment] 2020-04-15 23:04
I think this is fixed with recent miktex. If not, please post your `R-devel.log`

**Closed by jeroen** 2020-04-15 23:04 UTC
